gearopedia/models.py
import os
import logging

from gearopedia import db, app
from forms import FILE_TYPE

from flask import url_for, flash, redirect
from flask import session as login_session

from werkzeug import secure_filename
# from sqlalchemy.orm import db.relationship
# from sqlalchemy import db.Column, db.ForeignKey, db.Integer, db.String

# from datadb.Model import db.Model
ALLOWED_IMG_EXTENSIONS = app.config['ALLOWED_IMG_EXTENSIONS']
ALLOWED_EXTENSIONS = app.config['ALLOWED_EXTENSIONS']

class User(db.Model):

    __tablename__ = 'user'

    id = db.Column(db.Integer, primary_key=True)
    nickname = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)

    def __repr__(self):
        return '<User %r>' % (self.nickname)


class GearCategories(db.Model):
    """Categery model definition"""

    __tablename__ = 'category'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), nullable=False)
    user_id = db.Column(db.String, nullable=False)

    def __repr__(self):
        return '<Category name: %r, User ID: %r>' % (self.name, self.user_id)

    def delete_category(self):
        """Delete a gear category."""
        # Get list of child objects matching category
        models = \
            db.session.query(GearModels).filter_by(category_id=self.id).all()
        # Iterate through the list of objects calling their delete method
        for model in models:
            model.delete()
        # Delete instance of category
        db.session.delete(self)
        # Commit and return
        db.session.commit()


class GearModels(db.Model):
    """Gear Model model definition"""

    __tablename__ = 'model'

    id = db.Column(db.Integer, primary_key=True)
    manufacturer = db.Column(db.String(80), nullable=False)
    name = db.Column(db.String(80), nullable=False)
    description = db.Column(db.String(800))
    product_url = db.Column(db.String(2084))
    manual_url = db.Column(db.String(2084))
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'))
    category = db.relationship(GearCategories)
    user_id = db.Column(db.String, nullable=False)
    image_path = db.Column(db.String(250))

    def __repr__(self):
        return '<Model Name: %r, User ID: %r>' % (self.name, self.user_id)

    
    @property
    def serialize(self):
        """Serialize gear models for JSON export"""

        return {'manufacturer': self.manufacturer,
                'name': self.name,
                'description': self.description,
                'website': self.product_url,
                'category': self.category.name,
                'user_id': self.user_id
                }
    def delete(self):
        UploadedFiles.delete_files(self.id)
        Images.delete_image(self.id)
        db.session.delete(self)
        db.session.commit()

class Images(db.Model):
    """Image file model definition"""
    #TODO Refactor so images are just another file
    __tablename__ = 'image'

    id = db.Column(db.Integer, primary_key=True)
    file_name = db.Column(db.String(80), nullable=False)
    path = db.Column(db.String(250), nullable=False)
    model_id = db.Column(db.Integer, db.ForeignKey('model.id'))
    model = db.relationship(GearModels)
    user_id = db.Column(db.String, nullable=False)

    def __repr__(self):
        return '<File name: %r, User ID: %r>' % (self.file_name, self.user_id)

    @staticmethod
    def allowed_image(filename):
        """Returns filename if the filename extension is in ALLOWED_IMG_EXTENSIONS."""
        return '.' in filename and filename.rsplit('.', 1)[1] in ALLOWED_IMG_EXTENSIONS

    @classmethod
    def add_image(cls, upload_image, model_id):
        """Upload image file and tag the image to the model.

        Keyword arguments
        upload_image --- image file to upload
        model_id -- database id of the model"""

        # Erase existing upload_image if it exists
        cls.delete_image(model_id)
        # check filename extension and make secure
        if not cls.allowed_image(upload_image.filename):
            raise TypeError
        filename = secure_filename(upload_image.filename)
        if not filename:
            raise TypeError

        # Save file
        upload_image.save(os.path.join(app.config['UPLOAD_IMG_FOLDER'], filename))
        path = url_for('uploaded_img', filename=filename)
        # create new image
        image = cls(file_name=filename,
                       model_id=model_id,
                       user_id=login_session['name'],
                       path=path)
        db.session.add(image)
        db.session.commit()
        return path

    @classmethod
    def delete_image(cls, model_id):
        """Erase images file for model.

        Keyword arguments
        model_id ---  database id of the model"""
        try:
            image = db.session.query(cls).filter_by(model_id=model_id).one()
            # delete image
            if image:
                try:
                    os.remove(os.path.join(app.config['UPLOAD_IMG_FOLDER'], image.file_name))
                except OSError:
                    logging.info("File did not exist")
                session.delete(image)
                session.commit()
        except:
            logging.info("No images exist")



class UploadedFiles(db.Model):
    """Uploaded files model definition"""

    __tablename__ = 'file'

    id = db.Column(db.Integer, primary_key=True)
    file_name = db.Column(db.String(80), nullable=False)
    file_type = db.Column(db.String(80), nullable=False)
    path = db.Column(db.String(250), nullable=False)
    model_id = db.Column(db.Integer, db.ForeignKey('model.id'))
    model = db.relationship(GearModels)
    user_id = db.Column(db.String, nullable=False)

    def __repr__(self):
        return '<File name: %r, User ID: %r>' % (self.file_name, self.user_id)   

    @classmethod
    def allowed_image(cls, filename):
        """Returns filename if the filename extension is in ALLOWED_IMG_EXTENSIONS."""
        return '.' in filename and filename.rsplit('.', 1)[1] in ALLOWED_IMG_EXTENSIONS

    @staticmethod
    def allowed_file(filename):
        """Returns filename if the filename extension is in ALLOWED_EXTENSIONS."""
        return '.' in filename and filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS

    @classmethod
    def add_file(cls, upload_file, file_type, model_id, edit=None):
        """
        Adds file to database, and writes file to server.
        If the model already has a file of the same type, the old file
        is deleted in the database and from the server and the new file
        is written.

        Keyword arguments
        edit -- a flag indicated the function was called from and edit
                operation
        """

        # Query existing files
        if edit:
            model_files = \
                db.session.query(cls).filter_by(model_id=model_id)
            map(cls.delete_file, [model_file.id for model_file in model_files if model_file.file_type == FILE_TYPE[file_type]])

        # check filename extension and make secure
        if not cls.allowed_file(upload_file.filename):
            raise TypeError
        filename = secure_filename(upload_file.filename)
        if not filename:
            raise TypeError

        # Save file
        upload_file.save(os.path.join(app.config['UPLOAD_FOLDER'], filename))

        # Create new UploadedFiles object
        path = url_for('uploaded_file', filename=filename)
        model_file = cls(file_name=filename,
                                   file_type=FILE_TYPE[file_type],
                                   model_id=model_id,
                                   user_id=login_session['name'],
                                   path=path)
        db.session.add(model_file)
        db.session.commit()
        return path


    @classmethod
    def delete_file(cls, id):
        """Delete the file from the database and server.

        Keyword arguments
        id --- database id of the uploaded file
        """
        uploaded_file = db.session.query(cls).filter_by(id=id).one()
        db.session.delete(uploaded_file)
        db.session.commit()
        try:
            os.remove(os.path.join(app.config['UPLOAD_FOLDER'], uploaded_file.file_name))
        except OSError:
            logging.error("File does not exist")            

    @classmethod
    def delete_files(cls, model_id):
        """Delete all files associated with model.

        Keyword arguments
        model_id --- database id of the model to delete files from
        """

        files = db.session.query(cls).filter_by(model_id=model_id)
        # delete files if they exist
        if files:
            map(cls.delete_file, [f.id for f in files])

gearopedia/gear_models/views.py
import sqlalchemy
from flask import render_template, url_for, request, redirect, flash, jsonify, Blueprint
from flask import session as login_session

from ..models import GearCategories, GearModels, UploadedFiles, Images
from ..forms import ModelForm
from gearopedia import app, db
# import db.db_session as session
from ..utils import login_required


session = db.session

CLIENT_ID = app.config['CLIENT_ID']

gear_models_blueprint = Blueprint(
    'gearModels', __name__,
    template_folder='templates')


# Individual gear model handlers


@gear_models_blueprint.route('/add_item/<int:category_id>/', methods=['GET', 'POST'])
@login_required
def addmodel(category_id):
    """Create a new gear model."""
# Retrieve category from DB
    category = \
        session.query(GearCategories).filter_by(id=category_id).one()
    # Handle POST requests
    if request.method == 'POST':
        # Render form, validate data
        form = ModelForm(request.form)
        if not form.validate():
            flash('There was an error on the form %s.' % form.errors)
            return render_template('model_form.html',
                                   form=form,
                                   category=category,
                                   login_session=login_session,
                                   CLIENT_ID=CLIENT_ID, )
        # create new model object    
        model = GearModels(category=category,
                           user_id=login_session['name'])
        form.populate_obj(model)
        
        # check for image upload if it exists
        image = request.files['image']
        if image:
            model.image_path = Images.add_image(image, model.id)
        session.add(model)
        session.commit()
        flash('New model created, File Type is %s' % form.file_type.data)
        
        # check for file upload if one exists
        uploaded_file = request.files['file']
        
        if uploaded_file:
            try:
                UploadedFiles.add_file(uploaded_file, form.file_type.data, model.id, edit=True)
                flash('File upload successful')
            except TypeError:
                flash('File type incorrect')
            except OSError:
                flash('File upload error')
        print "redirect model.category_id = %s" % model.category_id
        return redirect(url_for('gearModels.viewmodels',
                                category_id=model.category_id))
    else:
        # Handle GET requests
        form = ModelForm()
        return render_template('model_form.html',
                               form=form,
                               category=category,
                               login_session=login_session,
                               CLIENT_ID=CLIENT_ID)


@gear_models_blueprint.route('/view_items/<int:category_id>/')
def viewmodels(category_id):
    """View all models for a given category."""
    try:    
        models = \
            session.query(GearModels).filter_by(category_id=category_id).order_by(GearModels.manufacturer).all()
    except sqlalchemy.orm.exc.NoResultFound:
        flash('Page not found')
        return redirect(url_for('default'))
    
    try:
        category = \
            session.query(GearCategories).filter_by(id=category_id).one()
    except sqlalchemy.orm.exc.NoResultFound:
        flash('Page not found')
        return redirect(url_for('default'))
    files = session.query(UploadedFiles).all()
    images = session.query(Images).all()
    return render_template('view_models.html',
                           title="Models",
                           models=models,
                           category_id=category_id,
                           category=category,
                           login_session=login_session,
                           files=files,
                           images=images,
                           CLIENT_ID=CLIENT_ID)


@gear_models_blueprint.route('/edit_model/<int:model_id>/', methods=['GET', 'POST'])
@login_required
def editmodel(model_id):
    """Edit a gear model."""
    try:
        model = session.query(GearModels).filter_by(id=model_id).one()
    except sqlalchemy.orm.exc.NoResultFound:
        flash('Page not found')
        return redirect(url_for('default'))
    if request.method == 'POST':
        form = ModelForm(request.form, )
        # Validate form data
        if not form.validate():
            return render_template('model_form.html',
                                   title="Edit Model",
                                   form=form,
                                   model=model,
                                   category=model.category,
                                   login_session=login_session,
                                   CLIENT_ID=CLIENT_ID)
        form.populate_obj(model)
        # Retrieve updated image if it exists and upload it
        image = request.files['image']
        if image:
            model.image_path = Images.add_image(image, model.id)
# add model to db
        session.add(model)
        session.commit()
        flash('Model %s edited' % model.name)

        # check for file upload if one exists
        model_file = request.files['file']
        if model_file:
            try:
                UploadedFiles.add_file(model_file, form.file_type.data, model.id, edit=True)
                flash('File upload successful')
            except TypeError:
                flash('File type incorrect')
            except OSError:
                flash('File upload error')
        return redirect(url_for('viewmodels',
                                category_id=model.category_id))
    else:

        # Handle GET requests

        form = ModelForm(obj=model, )
        return render_template('model_form.html',
                               form=form,
                               model=model,
                               category=model.category,
                               login_session=login_session,
                               CLIENT_ID=CLIENT_ID, 
                               )


@gear_models_blueprint.route('/delete_model/<int:model_id>/', methods=['GET', 'POST'])
@login_required
def deletemodel(model_id):
    """Delete a gear model."""

    # Verify user is logged in
    try:
        model = session.query(GearModels).filter_by(id=model_id).one()
    except sqlalchemy.orm.exc.NoResultFound:
        flash('Invalid ID')
        return redirect(url_for('default'))
    # Handle POST requests
    if request.method == 'POST':
        # Delete from DB
        # TODO add error checking
        model.delete()
        flash('Model %s deleted' % model.name)
        return redirect(url_for('viewmodels',
                                category_id=model.category_id))
    else:
        # Handle GET requests
        return render_template('delete_model.html',
                               model=model,
                               login_session=login_session,
                               CLIENT_ID=CLIENT_ID, )


# JSON Handler
@gear_models_blueprint.route('/json/')
def json_call():
    """Return JSON object off all categories and gear models."""
    models = session.query(GearModels).all()
    return jsonify(AllModels=[model.serialize for model in models])

gearopedia/gear_models/templates/add_model.html
{% extends "main.html" %}
{% block maincontent %}
<div>
<p><strong>Category:</strong> {{category.name}}</p>
<div>
   <form action='{{url_for('gearModels.addmodel', category_id=category.id)}}' method="POST" enctype='multipart/form-data'>
   <p>
      <!--MANUFACTURER-->
   <div class="col-md-6">
      {{ form.manufacturer.label }}  
   </div>
   <div class="col-md-6">
      {{ form.manufacturer(class="field size1")  }}
   </div>
   {% if form.manufacturer.errors %}
   <ul class="errors">
      {% for error in form.manufacturer.errors %}
      {{ error }}
      {% endfor %}
   </ul>
   {% endif %}
   </p>
   <!--MODEL-->
   <p>
   <div>
      {{ form.name.label }}  {{ form.name(class="field size1")  }}
   </div>
   {% if form.name.errors %}
   <ul class="errors">
      {% for error in form.name.errors %}
      {{ error }}
      {% endfor %}
   </ul>
   {% endif %}
   </p>
   <!--DESCRIPTION-->
   <p>
   <div>
      {{ form.description.label }}  {{ form.description(class="field size2")  }}
   </div>
   {% if form.description.errors %}
   <ul class="errors">
      {% for error in form.description.errors %}
      {{ error }}
      {% endfor %}
   </ul>
   {% endif %}
   </p>
   <!--MODEL URL-->
   <p>
   <div>
      {{ form.product_url.label }}  {{ form.product_url(class="field size1")  }}
   </div>
   {% if form.product_url.errors %}
   <ul class="errors">
      {% for error in form.product_url.errors %}
      {{ error }}
      {% endfor %}
   </ul>
   {% endif %}
   </p>
   <hr>
   <!--IMAGE UPLOAD-->
   <p>
   <div>
      {{ form.image.label }}  {{ form.image(class="field size1")  }}
   </div>
   {% if form.image.errors %}
   <ul class="errors">
      {% for error in form.image.errors %}
      {{ error }}
      {% endfor %}
   </ul>
   {% endif %}
   </p>
   <input type='file' name='image'>
   <!--FILE UPLOAD-->
   <p>
   <div>
      {{ form.file_type.label }}  {{ form.file_type(class="field size1")  }}
   </div>
   {% if form.file_type.errors %}
   <ul class="errors">
      {% for error in form.file_type.errors %}
      {{ error }}
      {% endfor %}
   </ul>
   {% endif %}
   </p>
   <input type='file' name='file'>
   </p>
   </hr>
   <hr>
   <input type="submit" value="Submit">
   </form>
   </hr>
</div>
{% endblock %}

gearopedia/gear_models/templates/delete_model.html
{% extends "main.html" %}
{% block maincontent %}
{% if login_session['name'] %}
<div>
   <form action='{{url_for('gearModels.deletemodel', model_id=model.id)}}' method="POST" enctype='multipart/form-data'>
   <h3>Model to delete: {{ model.name }}</h3>
   <input id='button' type="submit" value="Confirm Delete">
   </form>
</div>
{% endif %}
{% endblock %}

gearopedia/gear_models/templates/model_form.html
{% extends "main.html" %}
{% block maincontent %}
<div>
   <div class="row">
      <div class="col-md-12">
         <div class="panel panel-default" style="margin:15px;">
      
         <div class="panel-heading">Category: {{category.name}}</div>
            <div class="panel-body" style="background-color:#888; padding:10px;"> 
      
   
      
      <!--Model Form-->
      {% if model %}
      <form action='{{url_for('gearModels.editmodel', model_id=model.id)}}' method="POST" enctype='multipart/form-data'>
      
      {% else %}
      <form action='{{url_for('gearModels.addmodel', category_id=category.id)}}' method="POST" enctype='multipart/form-data'>
      {% endif %}
      {{ form.hidden_tag() }}
      {% if form.csrf_token.errors %}
         <div class="row">
            <div class="col-md-12">
               <ul class="errors">
                  {% for error in form.csrf_token.errors %}
                  {{ error }}
                  {% endfor %}
               </ul>
            </div>
         </div>
         {% endif %}
      <!--MANUFACTURER-->
      <div class="row">
         <div class="col-md-3">
            {{ form.manufacturer.label }}  
         </div>
         <div class="col-md-9">
            {{ form.manufacturer(class="field_size1")  }}
         </div>
         {% if form.manufacturer.errors %}
         <div class="row">
            <div class="col-md-12">
               <ul class="errors">
                  {% for error in form.manufacturer.errors %}
                  {{ error }}
                  {% endfor %}
               </ul>
            </div>
         </div>
         {% endif %}
      </div>
      <!--MODEL-->
      <div class="row">
         <div class="col-md-3">
            {{ form.name.label }}  
         </div>
         <div class="col-md-9">	
            {{ form.name(class="field_size1")  }}
         </div>
         {% if form.name.errors %}
         <ul class="errors">
            {% for error in form.name.errors %}
            {{ error }}
            {% endfor %}
         </ul>
         {% endif %}
      </div>
      <!--DESCRIPTION-->
      <div class="row">
         <div class="col-md-3">
            {{ form.description.label }}  
         </div>
         <div class="col-md-9">	
            {{ form.description(class="field_size1")  }}
         </div>
         {% if form.description.errors %}
         <ul class="errors">
            {% for error in form.description.errors %}
            {{ error }}
            {% endfor %}
         </ul>
         {% endif %}
      </div>
      <!--MODEL URL-->
      <div class="row">
         <div class="col-md-3">
            {{ form.product_url.label }}  
         </div>
         <div class="col-md-9">	
            {{ form.product_url(class="field_size1")  }}
         </div>
         {% if form.product_url.errors %}
         <ul class="errors">
            {% for error in form.product_url.errors %}
            {{ error }}
            {% endfor %}
         </ul>
         {% endif %}
      </div>
      <!--IMAGE UPLOAD-->
      <div class="row">
         <div class="col-md-3">
            {{ form.image.label }}  
         </div>
         <div class="col-md-9">
            <input type='file' name='image'>
         </div>
         <!-- <div class="col-md-9">	
            {{ form.image(class="field_size2")  }}
            </div> -->
         <div class="col-md-12">
            {% if form.image.errors %}
            <ul class="errors">
               {% for error in form.image.errors %}
               {{ error }}
               {% endfor %}
            </ul>
            {% endif %}
         </div>
      </div>
      <!--FILE UPLOAD-->
      <div class="row">
         <div class="col-md-3">
            {{ form.file_type.label }}  
         </div>
         <div class="col-md-3">	
            {{ form.file_type()  }}
         </div>
         <div class ="col-md-6">
            <input type='file' name='file'>
         </div>
         <!--<input type='file' name='file'>
            </div>
            <div class="col-md-12">-->
         {% if form.file.errors %}
         <ul class="errors">
            {% for error in form.file.errors %}
            {{ error }}
            {% endfor %}
         </ul>
         {% endif %}
      </div>
   

   <div class="row">
      <div class="col-md-12" >
    
         <input class="btn btn-default" type="submit" value="Submit" style="float:right; margin:15px;">
         </div>
   </div>
</div>
</div>
   </div>
         {% if login_session['user_id'] == "105472301115132080682"%}
         {% if model %}
         <div class="row" style="margin-left:15px; margin-bottom:50px">
             <div class="col-md-12">
              
         <a href='{{url_for('gearModels.deletemodel', model_id=model.id)}}'><span class="glyphicon glyphicon-remove" aria-hidden="true">Delete</span></a>
            </div>
         </div>
         {% endif %}
         {% endif %}
   </form>
</div>
</div>
</div>
{% endblock %}

gearopedia/gear_models/templates/view_models.html
{% extends "main.html" %}
{% block maincontent %}

                        
<!--<div class="panel panel-default" style="background-color:#888; margin:15px">
   <div class="panel-heading">{{category.name}}</div>-->
<ul class="list-group" style="margin:15px; ">   
<!--<div class="list-group" style="background-color:#888; margin:15px">-->
{% for model in models %}

   <li class="list-group-item" style="background-color:#888; padding:10px;">
      <div class="row">

   <!--<div class="panel-body" >-->
         <div class="col-md-5">   
         <div class="col-xs-12">
            {% if model.product_url != "" %}
            <a href='{{model.product_url}}'>{{model.manufacturer}}<br>{{model.name}}</a>
            {% else %}
            <a  href='#'>{{model.manufacturer}}<br>{{model.name}}  </a>
            {% endif %}
         </div>
         </div>
         <div class="col-md-3"> 
         <div class="col-xs-12">
            <img class="img-circle" src="{{model.image_path}}">
         </div>
         </div>
         <div class="col-md-4">
         <div class="col-xs-12">
            {% if login_session['name'] %}
            
            <div class="dropdown">
             <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" >
             Downloads
            <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1" style="margin-right:10px;">
            {% if files %}
            {% for file in files %}
            {% if file.model_id == model.id %}
            <li><a href='{{file.path}}'>{{file.file_type}}</a></li>
            {% endif %}
            {% endfor %}
            {% endif %}
            <li role="separator" class="divider"></li>
            <li><a href='{{url_for('gearModels.editmodel', model_id=model.id)}}'>Edit</a></li>
            </ul>
            </div>
            
         </div>
         </div>
         {% endif %}
     </div>
   </li>




{% endfor %}
</ul>


{% if login_session['name'] %}

<div class = "row" style="margin-left:15px; margin-bottom:50px">
<div class="col-xs-12" >
   
   <a href='{{url_for('gearModels.addmodel', category_id = category_id)}}'><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add New Model</a>
</div>
</div>
{% endif %}
{% endblock %}