gearopedia/categories/views.py
import sqlalchemy
from flask import render_template, url_for, request, redirect, flash, Blueprint
from flask import session as login_session

from ..models import GearCategories
from ..forms import AddCategoryForm
from gearopedia import app, db
# import db.db_session as session
from ..utils import login_required


session = db.session

CLIENT_ID = app.config['CLIENT_ID']


categories_blueprint = Blueprint(
    'categories', __name__,
    template_folder='templates')


# Category Handlers
@categories_blueprint.route('/add_category/', methods=['GET', 'POST'])
@login_required
def addgearcategory():
    """Create a new gear category."""
    if request.method == 'POST':
        form = AddCategoryForm(request.form, )
        # Validate form data, re-render form if there are errors
        if not form.validate():
            # render form with errors
            return render_template('add_category.html',
                                   form=form,
                                   login_session=login_session,
                                   CLIENT_ID=CLIENT_ID)
        # Store new category in DB
        new_category = GearCategories(name=form.name.data,
                                      user_id=login_session['name'])
        session.add(new_category)
        session.commit()
        flash('New category added')
        return redirect(url_for('home.default'))
    else:  # Handle GET requests
        form = AddCategoryForm()
        return render_template('add_category.html',
                               form=form,
                               login_session=login_session,
                               CLIENT_ID=CLIENT_ID)


@categories_blueprint.route('/delete_category/<int:category_id>/', methods=['GET', 'POST'])
@login_required
def deletegearcategory(category_id):
    """Delete a gear category."""
    try:
        category = \
            session.query(GearCategories).filter_by(id=category_id).one()
    except sqlalchemy.orm.exc.NoResultFound:
        flash('Error deleting')
        return redirect(url_for('default'))
    if request.method == 'POST':
        category.delete_category()
        flash('Category %s deleted' % category.name)
        return redirect(url_for('home.default'))
    else:
        return render_template('delete_category.html',
                               category=category,
                               login_session=login_session,
                               CLIENT_ID=CLIENT_ID, )

gearopedia/home/views.py
from flask import render_template, request, flash, Blueprint
from flask import session as login_session
from oauth2client import client, crypt

from ..models import GearCategories
from gearopedia import app, db

# import db.db_session as session

session = db.session
CLIENT_ID = app.config['CLIENT_ID']

home_blueprint = Blueprint(
    'home', __name__,
    template_folder='templates'
)


@home_blueprint.route('/')
def default():
    """Render home page."""
    categories = session.query(GearCategories).all()
    return render_template('default.html',
                           title="Categories",
                           categories=categories,
                           login_session=login_session,
                           page_title='Categories',
                           CLIENT_ID=CLIENT_ID)


# Login/Logout Handlers
@home_blueprint.route('/tokensignin', methods=['POST'])
def tokensignin():
    """Login user if valid id_token exists in request."""
    token = request.form['idtoken']
    try:
        idinfo = client.verify_id_token(token, CLIENT_ID)
        if idinfo['iss'] not in ['accounts.google.com', 'https://accounts.google.com']:
            raise crypt.AppIdentityError("Wrong issuer.")
    except crypt.AppIdentityError:
        raise crypt.AppIdentityError("Login Failed")
    login_session['user_id'] = idinfo['sub']
    login_session['name'] = idinfo['name']
    login_session['provider'] = "Google"
    if 'picture' in idinfo:
        login_session['picture'] = idinfo['picture']
    else:
        login_session['picture'] = "https://upload.wikimedia.org/wikipedia/commons/7/70/User_icon_BLACK-01.png"
    response = "Login Success"
    return response


@home_blueprint.route('/tokensignout', methods=['POST'])
def tokensignout():
    """Logout user if valid id_token exists in request."""
    token = request.form['idtoken']
    try:
        idinfo = client.verify_id_token(token, CLIENT_ID)
        if idinfo['iss'] not in ['accounts.google.com', 'https://accounts.google.com']:
            raise crypt.AppIdentityError("Wrong issuer.")
    except crypt.AppIdentityError:
        raise crypt.AppIdentityError("Logout Failed")
    del login_session['user_id']
    del login_session['name']
    del login_session['picture']
    del login_session['provider']
    response = "Logout Success"
    session.close()
    return response

# Error Handlers


@home_blueprint.errorhandler(400)
def not_found_error(error):
    flash('PAGE NOT FOUND')
    return render_template('404.html', login_session=login_session), 404


@home_blueprint.errorhandler(404)
def not_found_error(error):
    flash('PAGE NOT FOUND')
    return render_template('404.html', login_session=login_session), 404


@app.errorhandler(500)
def internal_error(error):
    session.rollback()
    flash('SOMETHING BROKE!')
    return render_template('500.html', login_session=login_session), 500

gearopedia/home/templates/default.html
{% extends "main.html" %}
{% block maincontent %}
<ul class="list-group" style="margin:15px; ">  
{% for category in categories %}
<li class="list-group-item" style="background-color:#888; padding:10px;">
     
<div class="row">
   <div class="col-xs-12" >
      <a  href='{{url_for('gearModels.viewmodels', category_id = category.id)}}'>{{category.name}}</a>
   </div>
</div>
{% if login_session['user_id'] == "105472301115132080682"%}
<div class="row">
   
   <div class="col-xs-12 col-md-12">
      <a href='{{url_for('categories.deletegearcategory', category_id = category.id)}}'><span class="glyphicon glyphicon-remove" aria-hidden="true">Delete</span></a>
   </div>
</div>
{% endif %}
</li>
{% endfor %}
</ul>
{% if login_session['name'] %}
<div class="row" style="margin-left:15px; margin-bottom:50px">
   <div class="col-xs-12" >
      <a href='{{url_for('categories.addgearcategory')}}'><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Add New Category</a>
   </div>
</div>
{% endif %}
{% endblock %}

gearopedia/home/templates/main.html
<!DOCTYPE html>
<html>
<head>
    {% if title %}
    <title>{{ title }} - gearopedia</title>
    {% else %}
    <title>gearopedia</title>
    {% endif %}
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="profile email" name="google-signin-scope">
    <meta content="{{CLIENT_ID}}" name="google-signin-client_id">
    <!-- CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/style.css" rel="stylesheet">
    <link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
    <!--Google Scripts-->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js">
    </script>
    <script src="https://apis.google.com/js/client:platform.js?onload=start" async defer>
    </script>
    <script src="https://apis.google.com/js/client.js?onload=init"></script>
    <script async="" defer src="https://apis.google.com/js/platform.js"></script>
    <script src=
    "https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!--Bootstrap Scripts-->
    <script src=
    "http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <script>

    function onSignIn(googleUser) {
        var id_token = googleUser.getAuthResponse().id_token;
        var xhr = new XMLHttpRequest();
        var url = "http://" + self.location.host + "/tokensignin"; 
        xhr.open('POST', url);
        xhr.setRequestHeader('Content-Type','application/x-www-form-urlencoded');
        xhr.onload = function() {
            console.log('Status ' + xhr.responseText);
            };
        xhr.send('idtoken=' + id_token);
        {% if not login_session['name'] %}
            setTimeout(function() {
                window.location.href = window.location.pathname;
            }, 400);
        {% endif %}
    }

    function signOut() {
        var auth2 = gapi.auth2.getAuthInstance();
        user = auth2.currentUser.get();
        id_token = auth2.currentUser.get().getAuthResponse().id_token;
        var xhr = new XMLHttpRequest();
        var url = "http://" + self.location.host + "/tokensignout";
        xhr.open('POST', url);
        xhr.setRequestHeader('Content-Type','application/x-www-form-urlencoded');
        xhr.onload = function() {
            console.log('Status ' + xhr.responseText);
            };
        xhr.send('idtoken=' + id_token);
        auth2.signOut().then(function() {
            console.log('User signed out.');
            setTimeout(function() {
                window.location.href = window.location.pathname;
            }, 400);
        });
    }
    function signincallback() {
        setTimeout(function() {
        window.location.href = window.location.pathname;
        }, 3000);
    }             
   </script>
</head>
<body>
    <div class="container">
        <!--NEW NAV BAR OPEN -->
        <nav class="navbar navbar-default" style="margin-top:15px;">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">Gearopedia</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav" style="float:right;">
                    
            {% if login_session['provider']=="Google" %}
                <li>
                <div class="g-signin2" data-onsuccess="onSignIn" data-theme="light" style="padding:5px;">
                </div>
                </li>
            {% else %}
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Login<span class="caret"></span></a>
                <ul class="dropdown-menu">
        
            
                 <li> <div class="g-signin2" 
                                        
                                        data-onsuccess="onSignIn"
                                        
                                        data-theme="light" 
                                        style="padding:5px;" 
                                        >
                                        
                </div></li>
               </ul>
        </li>
            {% endif %}
            {% if login_session['name'] %}
                    
                    <li>
                        <a style=" float:right;" href="#" onclick="signOut();">Logout</a>
                    </li>
                    
                    {% endif %}
              
              <!--<form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
              </form>-->
              </ul>
              
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
        <!-- NEW NAVBAR CLOSE -->
               
        <!-- messaging -->
        {% with messages = get_flashed_messages() %} {% if messages %}
        <div class="bs-example bs-example-standalone" data-example-id="dismissible-alert-js">
            <div class="alert alert-warning alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    {% for message in
                    messages%}
                    <strong>{{ message }}</strong> 
                    {% endfor %}
            </div>
        </div>
        {% endif %} {% endwith %}
        <!-- close messaging -->
        <div class="row">
            <div class='col-sm-6'></div>
        </div>
       
        <div class ="row">
            <div class="span12">
                {% block maincontent %} {% endblock %}  
            <!--close span-->
            </div>
        <!--close row-->
        </div>
    <!--close container-->
    </div>
</body>
</html>